emde.kz/Controllers/HospitalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using emde.kz.DAL;
using emde.kz.Models;

namespace emde.kz.Controllers
{
    public class HospitalsController : Controller
    {
        private MedicinesContext db = new MedicinesContext();

        // GET: Hospitals
        public ActionResult Index(string sortOrder, string searchHospital, string region)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            
            var hospitals = db.Hospitals.Include(h => h.City);

            switch (sortOrder)
            {
                case "name_desc":
                    hospitals = hospitals.OrderByDescending(s => s.Name);
                    break;
                default:
                    hospitals = hospitals.OrderBy(s => s.Name);
                    break;
            }

            if (!String.IsNullOrEmpty(searchHospital))
            {
                hospitals = hospitals.Where(s => s.Name.Contains(searchHospital)
                                            || s.Address.Contains(searchHospital));
            }

            var RegionLst = new List<string>();
            var RegionQry = from t in db.Hospitals
                             orderby t.City.CityName
                             select t.City.CityName;
            RegionLst.AddRange(RegionQry.Distinct());
            ViewBag.region = new SelectList(RegionLst);

            if (!String.IsNullOrEmpty(region))
            {
                hospitals = hospitals.Where(x => x.City.CityName == region);
            }

            return View(hospitals.ToList());
        }

        // GET: Hospitals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital hospital = db.Hospitals.Find(id);
            if (hospital == null)
            {
                return HttpNotFound();
            }
            return View(hospital);
        }

        // GET: Hospitals/Create
        public ActionResult Create()
        {
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "CityName");
            return View();
        }

        // POST: Hospitals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Address,PhoneNumber,Email,Website,SrcYandex,CityID")] Hospital hospital)
        {
            if (ModelState.IsValid)
            {
                db.Hospitals.Add(hospital);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CityID = new SelectList(db.Cities, "CityID", "CityName", hospital.CityID);
            return View(hospital);
        }

        // GET: Hospitals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital hospital = db.Hospitals.Find(id);
            if (hospital == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "CityName", hospital.CityID);
            return View(hospital);
        }

        // POST: Hospitals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Address,PhoneNumber,Email,Website,SrcYandex,CityID")] Hospital hospital)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hospital).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "CityName", hospital.CityID);
            return View(hospital);
        }

        // GET: Hospitals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hospital hospital = db.Hospitals.Find(id);
            if (hospital == null)
            {
                return HttpNotFound();
            }
            return View(hospital);
        }

        // POST: Hospitals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hospital hospital = db.Hospitals.Find(id);
            db.Hospitals.Remove(hospital);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

emde.kz/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using emde.kz.DAL;
using emde.kz.Models;

namespace emde.kz.Controllers
{
    public class MedicinesController : Controller
    {
        private MedicinesContext db = new MedicinesContext();

        // GET: Medicines
        public ActionResult Index(string sortOrder, string searchMedicine, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;

            if (searchMedicine != null)
            {
                page = 1;
            }
            else
            {
                searchMedicine = currentFilter;
            }

            ViewBag.CurrentFilter = searchMedicine;

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            var medicines = from s in db.Medicines
                            select s;

            if (!String.IsNullOrEmpty(searchMedicine))
            {
                medicines = medicines.Where(s => s.Name.Contains(searchMedicine)
                                                || s.InternationalName.Contains(searchMedicine));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    medicines = medicines.OrderByDescending(s => s.Name);
                    break;
                default:
                    medicines = medicines.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 7;
            int pageNumber = (page ?? 1);
            return View(medicines.ToPagedList(pageNumber, pageSize));
        }

        // GET: Medicines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }

            return View(medicine);
        }

        // GET: Medicines/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Medicines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Type,Country,Company,InternationalName,Component,PharmaAction,Contrindiction,Effect,MethodsOfUse,StorageCondition,Image,Dosage,Recipe")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                db.Medicines.Add(medicine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medicine);
        }

        // GET: Medicines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: Medicines/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Type,Country,Company,InternationalName,Component,PharmaAction,Contrindiction,Effect,MethodsOfUse,StorageCondition,Image,Dosage,Recipe")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medicine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(medicine);
        }

        // GET: Medicines/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: Medicines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medicine medicine = db.Medicines.Find(id);
            db.Medicines.Remove(medicine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

emde.kz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="yandex-verification" content="1bb3f91d2d6b3ab2" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="@ViewBag.Description">
    <meta name="keywords" content="Больница, клиника, больницы Алматы, клиника Алматы, лекарства, инструкция лекарств">
    <meta name="image" content="@ViewBag.Image" class="pulse" />
    
    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="@ViewBag.Image" />
    <meta property="og:url" content="@ViewBag.Url" />
    <meta property="og:description" content="@ViewBag.Description" />
    <meta property="og:image:width" content="100" />
    <meta property="og:image:height" content="100" />
    
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="@ViewBag.Title" />
    <meta name="twitter:description" content="@ViewBag.Description" />
    <meta name="twitter:image" content="@ViewBag.Image" />
    <script type="text/javascript" src="http://vk.com/js/api/share.js?94" charset="windows-1251"></script>
    <script src="https://vk.com/js/api/openapi.js?135" type="text/javascript"></script>
    <link rel=" shortcut icon" href="~/Images/pulse.png">
    <title> @ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="fb-root"></div>
    <script>
(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8&appId=567111583481161";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
    </script>  
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Лекарства", "Index", "Medicines", null, new { @class = "main-icon" })</li>
                    <li>@Html.ActionLink("О Нас", "About", "Home", null, new { @class = "main-icon" })</li>
                    <li>@Html.ActionLink("Больницы и клиники", "Index", "Hospitals", null, new { @class = "main-icon" })</li>
                    <li>@Html.ActionLink("Пользовательское соглашение", "Contact", "Home", null, new { @class = "main-icon" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer>
        <div class="footer-left">
            <p>@Html.ActionLink("Лекарства", "Index", "Medicines", null, new { @class = "main-icon-footer" })</p>
            <p>@Html.ActionLink("О Нас", "About", "Home", null, new { @class = "main-icon-footer" })</p>
            <p>@Html.ActionLink("Больницы и клиники", "Index", "Hospitals", null, new { @class = "main-icon-footer" })</p>
            <p>@Html.ActionLink("Пользовательское соглашение", "Index", "Home", null, new { @class = "main-icon-footer" })</p>
            <br /><br /><br />
            <span>&copy; @DateTime.Now.Year - emdeme.azurewebsites.net</span>
        </div>
        <div class="footer-right">
            <!-- HotLog -->
            <span id="hotlog_counter"></span>
            <span id="hotlog_dyn"></span>
            <script type="text/javascript">
             var hot_s = document.createElement('script');
                hot_s.type = 'text/javascript'; hot_s.async = true;
                hot_s.src = 'http://js.hotlog.ru/dcounter/2539436.js';
                hot_d = document.getElementById('hotlog_dyn');
                hot_d.appendChild(hot_s);
            </script>
            <noscript>
                <a href="http://click.hotlog.ru/?2539436" target="_blank">
                    <img src="http://hit19.hotlog.ru/cgi-bin/hotlog/count?s=2539436&im=407" border="0"
                         title="HotLog" alt="HotLog">
                </a>
            </noscript>
            <!-- /HotLog -->

            <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
                })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

                ga('create', 'UA-86693953-1', 'auto');
                ga('send', 'pageview');
            </script>

            <!-- Yandex.Metrika counter -->
            <script type="text/javascript">
                (function (d, w, c) {
                    (w[c] = w[c] || []).push(function () {
                        try {
                            w.yaCounter40609420 = new Ya.Metrika({
                                id: 40609420,
                                clickmap: true,
                                trackLinks: true,
                                accurateTrackBounce: true
                            });
                        } catch (e) { }
                    });

                    var n = d.getElementsByTagName("script")[0],
                        s = d.createElement("script"),
                        f = function () { n.parentNode.insertBefore(s, n); };
                    s.type = "text/javascript";
                    s.async = true;
                    s.src = "https://mc.yandex.ru/metrika/watch.js";

                    if (w.opera == "[object Opera]") {
                        d.addEventListener("DOMContentLoaded", f, false);
                    } else { f(); }
                })(document, window, "yandex_metrika_callbacks");
            </script>
            <noscript><div><img src="https://mc.yandex.ru/watch/40609420" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
            <!-- /Yandex.Metrika counter -->

            <!-- ZERO.kz -->
            <span id="_zero_67854">
                <noscript>
                    <a href="http://zero.kz/?s=67854" target="_blank">
                        <img src="http://c.zero.kz/z.png?u=67854" width="88" height="31" alt="ZERO.kz" />
                    </a>
                </noscript>
            </span>

            <script type="text/javascript">
                var _zero_kz_ = _zero_kz_ || [];
                _zero_kz_.push(["id", 67854]);
                _zero_kz_.push(["type", 1]);

            (function () {
                var a = document.getElementsByTagName("script")[0],
                s = document.createElement("script");
                s.type = "text/javascript";
                s.async = true;
                s.src = (document.location.protocol == "https:" ? "https:" : "http:")
                + "//c.zero.kz/z.js";
                a.parentNode.insertBefore(s, a);
                })(); 
           </script>
            <!-- End ZERO.kz -->
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>